# Generated by Django 2.0.6 on 2018-06-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', verbose_name='Last Modified')),
                ('title', models.CharField(max_length=100, verbose_name='Company title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/logo/', verbose_name='Company logo')),
                ('background', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Background Picture')),
                ('fevicon', models.ImageField(blank=True, null=True, upload_to='fevicon/', verbose_name='Fevicon (Title Icon)')),
                ('story', models.TextField(verbose_name='Background story')),
                ('who', models.TextField(verbose_name='Who we are')),
                ('what', models.TextField(verbose_name='What we do')),
                ('contact_description', models.TextField(blank=True, verbose_name='Contact description')),
                ('address', models.TextField(verbose_name='Compay address')),
                ('phone1', models.CharField(max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
