# Generated by Django 2.0.6 on 2018-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords. Ex: abl, electrical, consulting, '),
        ),
    ]
