# Generated by Django 2.0.6 on 2018-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180609_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='address',
            field=models.TextField(blank=True, verbose_name='Compay address'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='brand',
            name='phone1',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
