# Generated by Django 2.0.6 on 2018-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180609_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='icon',
            field=models.TextField(),
        ),
    ]
