# Generated by Django 2.0.6 on 2018-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_client_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', null=True, verbose_name='Last Modified')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-created_at', 'email'],
                'verbose_name_plural': 'Newsletter subscribers',
                'verbose_name': 'Newsletter subscriber',
            },
        ),
    ]
