# Generated by Django 2.0.6 on 2018-06-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_at', 'email'], 'verbose_name': 'Email subscriber', 'verbose_name_plural': 'Email subscribers'},
        ),
    ]
