# Generated by Django 2.0.6 on 2018-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180614_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AddField(
            model_name='brand',
            name='team_description',
            field=models.TextField(blank=True, verbose_name='Team description'),
        ),
    ]
