# Generated by Django 2.0.6 on 2018-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180614_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, help_text='Recommended picture size is 400x499 pixels', null=True, upload_to='staff/'),
        ),
    ]
