# Generated by Django 2.0.6 on 2018-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20180630_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', null=True, verbose_name='Last Modified')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('content', models.TextField(verbose_name='Message')),
            ],
            options={
                'get_latest_by': ['-created_at'],
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
