# Generated by Django 2.0.6 on 2018-06-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', null=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
                'get_latest_by': ['-updated_at'],
                'verbose_name': 'Catagory',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', null=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('summary', models.TextField(blank=True, verbose_name='Short summary')),
                ('content', models.TextField(verbose_name='Post')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('open_for_comment', models.BooleanField(default=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.Catagory')),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', null=True, verbose_name='Last Modified')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['title'],
                'get_latest_by': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogs.Tag'),
        ),
    ]
