# Generated by Django 2.0.6 on 2018-06-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180627_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record first created date and time', null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last modified date and time', null=True, verbose_name='Last Modified')),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(blank=True, verbose_name='Short bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blogs.Author'),
        ),
    ]
