# Generated by Django 2.0.6 on 2018-06-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20180627_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
    ]
